---
- hosts: localhost
  tasks:    
    - name: get ec2 in my account
      ec2_instance_info:
        aws_access_key: "{{ lookup('env','id') }}"
        aws_secret_key: "{{ lookup('env','key') }}"        
        region: us-east-2
      register: ec2_info

    - name: describe the ec2 in detail
      debug:
        var: ec2_info
