---
name: one-test  # display as workflowname
on:
  push: 
    branches:
      - master
    paths:
      - 'sample/**'
    
jobs:
  one-latest: # identifier should have  no space but can use hiphen "-"
    name: test the scenario
    runs-on: ububtu-latest
    steps:
      - name: Checkout
        uses: actions/Checkout@master


####
