---
name: one-test
on:
  push: 
  branches:
    - master
  paths:
    - 'sample/**'
    
jobs:
  one-latest:
    name: test the scenario
    runs-on: ububtu-latest
    steps:
      - name: Checkout
        uses: actions/Checkout@master
